// <auto-generated />
namespace CRME.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class columnas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(columnas));
        
        string IMigrationMetadata.Id
        {
            get { return "202209282229576_columnas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
