// <auto-generated />
namespace CRME.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tablas_mtto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablas_mtto));
        
        string IMigrationMetadata.Id
        {
            get { return "202307062024055_tablas_mtto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
